spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
